name: Run script

on:
  issues:
    types: [opened, reopened, closed, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: false
    - name: Build docker
      run: |
        docker build -t "yes-recon:latest" "${DIR}"
        docker image ls
        echo Saving image..
        docker save --output yes-recon.tar yes-recon:latest
        sha256sum yes-recon.tar > checksum.txt
        split --verbose -b1G yes-recon.tar split_yes-recon.tar.

# Create release
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::ActionBuild_$(date +"%Y.%m.%d_%H-%M-%S")"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: checksum.txt
        append_body: true
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          ./split_*
          ./checksum.txt
# Done release
    - name: Run script
      run: |
        bash ./init.sh
        
